### PR TITLE
Add support for new typescriptreact filetype

### PR DESCRIPTION
**Pull request by iwikal**
I'm too impatient to wait for #167, so this is my attempt at applying the feedback given there. It seems to work with my config, but I haven't tested it very extensively.

### CODE REVIEW

**Comment by croaky** [comment]
I recently upgraded Vim and various dependencies. Started getting awkward syntax highlighting. 

Think it might have been due to recent changes to https://github.com/vim/vim/blob/master/runtime/syntax/typescript.vim and https://github.com/HerringtonDarkholme/yats.vim/blob/master/syntax/common.vim ?

Using the change in this PR fixed my issue. Thanks, @iwikal!

**Comment by leafgarland** [comment]
Now that vim has a typescript syntax etc bundled in the distribution this repo might be less useful. 

I’ll look at this when I get to a proper computer, thanks.

**Comment by croaky** [comment]
When I was debugging this, I did try removing this repo. I was able to get syntax highlighting into a decent place but lost high-quality jump to definition.

As a side note, I've been using this Vim plugin for over a year and it's provided a great service to me every working day; this was the first issue I bumped into in that time. Thanks for writing and maintaining the project, @leafgarland.

**Comment by nchase** [comment]
This PR seems to do the trick. Hope that something can be landed in master before too long!

**Comment by jwm** [comment]
Ubuntu 20.04 ships with a `vim` version that needs this change.

**Comment by SteffeyDev** [comment]
Worked great for me!

**Comment by PezCoder** [comment]
Spent my last 2 hours just managing to fix the highlighting post my :PlugUpdate, & finally landed here.

YATS (Yet another typescript syntax) is something which VIM has internally implemented as part of vim8, which just didn't work with my theme 'gruvebox' that well. The colors are just all over the place.

Have been using this theme forever now, & this branch manages to fix the 'filetype' update that has happened across neovim & VIM 8 where they've introduced two new filetypes `javascriptreact` & `typescriptreact`

Would request you to review & merge this PR if it looks good? @leafgarland @nilscc 🙇

**Comment by shirai91** [comment]
This PR works for me, please help to review this PR T_T

**Review by leafgarland — APPROVED** [review]

**Comment by leafgarland** [comment]
Thanks all, for the work and the chasing 👍

**Pull request merged**
