### PR TITLE
Use javascript indent

### PR DESCRIPTION
**Pull request by leafgarland**
Update the indent script to use the indent script from pangloss/vim-javascript.

### CODE REVIEW

**Comment by leafgarland** [comment]
@Ravencrow @jamiechoi @CodeOneTwo

Take a look at this PR, let me know if it works for you. Thanks!

**Comment by Ravencrow** [comment]
Mm... strange. I use vim-javascript for indentation of js files and it does correctly, but I updated this plugin and it doesn't work. Maybe it's a problem in my vimrc config...
I have used setlocal indentkeys+=0. and I have typescript_indent_disable to 0.
But nothing. It's not working.

**Comment by Ravencrow** [comment]
I copied the content of the indentation file on this pr to my typescript.vim/indent/typescript.vim file and it works like a charm!

**Comment by leafgarland** [comment]
Good to know. Will merge tomorrow. Thanks for testing.

**Pull request merged**
