### PR TITLE
Improve syntax folding

### PR DESCRIPTION
**Pull request by alexander-alzate**

### CODE REVIEW

**Comment by leafgarland** [comment]
Hello, thanks very much for the PR. Can you tell me what it improves?

**Comment by alexander-alzate** [comment]
Folding blank lines after code blocks making the code more readable.

**Comment by leafgarland** [comment]
Thanks. It is an interesting change and I can see that it improves the look of folds in some ways - but I'm not sure it is an appropriate change for everyone.

**Comment by leafgarland** [comment]
I just meant that it seems like a personal preference - I can easily imagine other folks not wanting to collapse the white space between folds. I don't use syntax based folding very often though - perhaps it is more common to do this than I think - are there many other cases of doing this for folds?

I use `marker` folding mostly (if I use it at all) and that does not include empty lines after a marker.

**Comment by alexander-alzate** [comment]
Well, [Vim-syntax-for-PHP](https://github.com/2072/vim-syntax-for-PHP.git) does fold white spaces and I get used to it.

**Comment by leafgarland** [comment]
I'm going to close this one, I can see that it works for you - but it looks like keeping the whitespace is more common for folding. Thanks.

**Pull request closed without merging**
