### PR TITLE
Add support for Symbols

### PR DESCRIPTION
**Pull request by whitneyit**
I'm not sure if there is anything else that needs to be accounted for, but my simple testing shows the patch working.

### CODE REVIEW

**Comment by leafgarland** [comment]
Hi, been away but will take a look soon. Thanks.

**Comment by leafgarland** [comment]
Hello again. Did you miss a change from that commit? I can't see any match definition for `typescriptSymbol`.

**Comment by whitneyit** [comment]
If memory serves me right, I think just searched for `boolean` and copy and pasted until the highlighting started working. Combine that with a rebase and it may have gotten lost 😞

I'll update the PR to also take into account the [well known symbols](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Well-known_symbols) as well as fixing the linking on `typescriptSymbol`

**Comment by whitneyit** [comment]
I have now removed the reference to `typescriptSymbol`

**Comment by leafgarland** [comment]
Thanks!

**Pull request merged**
